name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        cd .. && rm Catch2 -rf
    - name: Build
      run: |
        cmake --DGENERATE_DOCS=OFF --DENABLE_TESTING=OFF .
        cmake --build .
    - name: Test
      run: ctest .
